### ISSUE TITLE
Git URL for sane-backends seems to be broken

### ISSUE THREAD

**Issue by elsiehupp** [atomspring/Scansnap-ix500-Linux#4]
The following `git` URL appears to be broken:

```
# git clone git://git.debian.org/sane/sane-backends.git
Cloning into 'sane-backends'...
fatal: unable to connect to git.debian.org:
git.debian.org[0: 194.177.211.202]: errno=Connection refused
git.debian.org[1: 2001:648:2ffc:deb::211:202]: errno=Network is unreachable
```

The following URL seems to work as an alternative:

```# git clone https://salsa.debian.org/debian/sane-backends.git```

**Comment by atomspring** [comment]
Thanks @elsiehupp , I'll update this now.

Cool, didn't think anyone used this!
